### ISSUE TITLE
Check maintainers of repository

### ISSUE THREAD

**Issue by dblandin** [graphql/graphql-wg#211]
Re: Acceptance Criteria for Editorial Changes

Check maintainers of repository

assignee: @IvanGoncharov  
source: [GraphQL Working Group Meeting 2019-07-03
](https://github.com/graphql/graphql-wg/blob/ffbbdbac74e3e957c1dba814704c08ff02c35353/notes/2019-07-03.md#action-items)

**Comment by IvanGoncharov** [comment]
@dblandin Thanks a lot for creating these items 👍 

I have commit rights on `graphql-spec` so after Lee clarified acceptances criteria I went ahead and merged all non-controversial editorial PRs.
About getting the list of people who have commit rights it looks GitHub doesn't provide this info directly (maybe because I'm not an admin for this repo) but I found a neat trick you can get this list https://github.com/graphql/graphql-spec/issues/show_menu_content?partial=issues%2Ffilters%2Fauthors_content&q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
So it's looks like we already big list of people (and a few bots) that have commit rights.
So I think this action item is done ✅

I think as a procedure it would be useful to keep action item open until it's reviewed on WG meeting so we are sure that everyone is heard and we have consensus around it.
I went ahead and created label so now it's easy to find and review all of them:
https://github.com/graphql/graphql-wg/labels/Action%20item%20%3Aclapper%3A
As non-native speaker I'm not sure about clapper reference but I didn't think of anything that is better suited.

Also I think it would be great if someone will create issue template for specifically for "action item" since among other things issue templates supports automaticly assigning labels so no need for "Action Item: " prefix in the title.
https://help.github.com/en/articles/about-issue-and-pull-request-templates#issue-templates

@dblandin Do you want to work on this?

**Comment by dblandin** [comment]
> I think as a procedure it would be useful to keep action item open until it's reviewed on WG meeting so we are sure that everyone is heard and we have consensus around it.

Yep! I think this naturally falls into the "Review previous action items" section of the agenda. Sounds good!

> I went ahead and created label so now it's easy to find and review all of them

Awesome! Agreed. A label is a lot nicer than an issue title prefix :+1: 

> Also I think it would be great if someone will create issue template for specifically for "action item" since among other things issue templates supports automatically assigning labels so no need for "Action Item: " prefix in the title.

For sure. I'll open a PR adding an issue template. That's a great idea :100:

**Comment by dblandin** [comment]
@IvanGoncharov Are you able to update the assignees for the current action item issues? I've mentioned those appropriate in the PR description but I'm unable set assignees with my current contributor access.

**Comment by IvanGoncharov** [comment]
@dblandin Great suggestion 👍 I thought it impossible since previously you could assign issues only to account with commit right but seems like GitHub relaxed rules a bit:

> You can assign up to 10 people to each issue or pull request, including yourself, anyone who has commented on the issue or pull request, anyone with write permissions to the repository, and organization members with read permissions to the repository

Still, I can't assign people until they comment in the issue 😞
